name: CI/CD para Java

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-linux:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: lifesync
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root -proot || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Instalar dependências do MySQL
        run: sudo apt-get update && sudo apt-get install -y libmysqlclient-dev

      - name: Aguardar MySQL estar pronto
        run: |
          for i in {1..10}; do
            if mysql -h 127.0.0.1 -P 3306 -u root -proot -e "SELECT 1;" > /dev/null 2>&1; then
              echo "MySQL está pronto!";
              break;
            fi
            echo "Aguardando o MySQL...";
            sleep 5;
          done

      - name: Compilar e executar testes
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_NAME: lifesync
          DB_USER: root
          DB_PASS: root
        run: mvn clean verify


  test-macos:
    runs-on: macos-latest
    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Instalar e iniciar MySQL (macOS)
        run: |
          brew update
          brew install mysql
          brew services start mysql
          # Espera alguns segundos para o servidor iniciar
          sleep 10
          # Define a senha do root
          mysqladmin -u root password 'root'

      - name: Aguardar MySQL estar pronto (macOS)
        run: |
          for i in {1..10}; do
            if mysql -u root -proot -e "SELECT 1;" > /dev/null 2>&1; then
              echo "MySQL está pronto!";
              break;
            fi
            echo "Aguardando o MySQL (macOS)...";
            sleep 5;
          done

      - name: Criar Banco de Dados
        run: mysql -u root -proot -e "CREATE DATABASE IF NOT EXISTS lifesync;"

      - name: Compilar e executar testes
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_NAME: lifesync
          DB_USER: root
          DB_PASS: root
        run: mvn clean verify


  test-windows:
    runs-on: windows-latest
    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Instalar MySQL (Windows)
        run: choco install mysql --params '"/port:3306 /serviceName:MySQL /password:root"' -y
        
      - name: Definir senha root manualmente (Windows)
        run: mysqladmin -u root password root

      # - name: Aguardar MySQL estar pronto (Windows)
      #   shell: pwsh
      #   run: |
      #     $maxRetries = 10
      #     for ($i=1; $i -le $maxRetries; $i++) {
      #       if (mysql -u root -e "SELECT 1;" > $null 2>&1) {
      #         Write-Host "MySQL está pronto!"
      #         exit 0
      #       } else {
      #         Write-Host "Aguardando o MySQL (Windows)..."
      #         Start-Sleep -Seconds 5
      #       }
      #     }
      #     exit 1

      - name: Criar Banco de Dados
        run: mysql -u root -proot -e "CREATE DATABASE IF NOT EXISTS lifesync;"

      - name: Compilar e executar testes
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_NAME: lifesync
          DB_USER: root
          DB_PASS: root
        run: mvn clean verify
