name: CI/CD para Java com Testcontainers

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Configurar Docker para Testcontainers
        run: |
          echo "Configurando Docker para permitir acesso do Testcontainers"
          docker --version
          sudo chmod 666 /var/run/docker.sock

      - name: Configurar reuso de containers
        run: |
          echo "testcontainers.reuse.enable=true" > ~/.testcontainers.properties

      - name: Compilar e executar testes
        run: mvn clean verify

  test-macos:
    runs-on: macos-latest
    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Configurar Docker para Testcontainers
        run: |
          echo "Configurando Docker para permitir acesso do Testcontainers"
          docker --version
          sudo chmod 666 /var/run/docker.sock

      - name: Configurar reuso de containers
        run: |
          echo "testcontainers.reuse.enable=true" > ~/.testcontainers.properties

      - name: Compilar e executar testes
        run: mvn clean verify

  test-windows:
    runs-on: windows-latest
    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Instalar Docker no Windows
        run: |
          choco install docker-desktop -y
          Start-Service Docker
          docker --version

      - name: Configurar reuso de containers
        run: |
          echo "testcontainers.reuse.enable=true" > $env:USERPROFILE/.testcontainers.properties

      - name: Compilar e executar testes
        run: mvn clean verify
