name: CI/CD para Java

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Executar Testes em ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest] # Testar em múltiplos SOs

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Configurar MySQL
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          sudo service mysql start
          mysql -u root -e "CREATE DATABASE lifesync;"
          mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'root';"

      - name: Configurar MySQL no macOS
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install mysql
          brew services start mysql
          mysql -u root -e "CREATE DATABASE lifesync;"
          mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'root';"

      - name: Configurar MySQL no Windows
        if: runner.os == 'Windows'
        run: |
          choco install mysql --version=8.0 -y
          Start-Service mysql
          mysql -u root -e "CREATE DATABASE lifesync;"
          mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'root';"

      - name: Configurar variáveis de ambiente
        env:
          DB_HOST: localhost
          DB_PORT: 3306
          DB_NAME: lifesync
          DB_USER: root
          DB_PASS: root
        run: echo "Configuração concluída."

      - name: Compilar e executar testes
        run: mvn clean verify
