name: CI/CD para Java

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Executar Testes em ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest] # Adicionando suporte para Windows e macOS

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root --password=root || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: lifesync

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Instalar dependências do MySQL (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libmysqlclient-dev

      - name: Instalar dependências do MySQL (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install mysql --version=8.0 -y
          echo "MySQL instalado no Windows."

      - name: Instalar dependências do MySQL (macOS)
        if: runner.os == 'macOS'
        run: brew install mysql@8.0

      - name: Aguardar MySQL estar pronto
        run: |
          for i in {1..10}; do
            if mysql -h 127.0.0.1 -P 3306 -u root -proot -e "SELECT 1;" > /dev/null 2>&1; then
              echo "MySQL está pronto!";
              break;
            fi
            echo "Aguardando o MySQL...";
            sleep 5;
          done

      - name: Configurar variáveis de ambiente
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_NAME: lifesync
          DB_USER: root
          DB_PASS: root
        run: echo "Banco configurado."

      - name: Compilar e executar testes
        run: mvn clean verify
