name: CI/CD para Java

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Executar Testes em ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest] # Testar em múltiplos SOs

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Configurar MySQL
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libmysqlclient-dev

      - name: Configurar MySQL no macOS
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install mysql
          brew services start mysql

      - name: Configurar MySQL no Windows
        if: runner.os == 'Windows'
        run: |
          choco install mysql --version=8.0 -y
          Start-Service mysql

      - name: Aguardar MySQL estar pronto
        run: |
          for i in {1..10}; do
            if mysql -h 127.0.0.1 -P 3306 -u root -proot -e "SELECT 1;" > /dev/null 2>&1; then
              echo "MySQL está pronto!";
              break;
            fi
            echo "Aguardando o MySQL...";
            sleep 5;
          done          

      - name: Configurar variáveis de ambiente
        env:
          DB_HOST: localhost
          DB_PORT: 3306
          DB_NAME: lifesync
          DB_USER: root
          DB_PASS: root
        run: echo "Configuração concluída."

      - name: Compilar e executar testes
        run: mvn clean verify
